services:
  jekyll:
    # Use 'build' instead of 'image' to build the image from your local Dockerfile
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development